#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  mkdir "$shome/vendor"
  git clone git@github.com:articulate/tugboat "$shome/vendor/tugboat" || true
  cd "$shome/vendor/tugboat"
  git fetch
  git reset --hard "$TUGBOAT_VERSION"
}

main "$@"
