#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_tugboat="0.0.1"
  jq -n --arg tugboat "$ver_tugboat" '{tugboat: $tugboat}'
}

version "$@"
